neutron contract rpc
qtumproject/qtum-neutron pull request #5
Opened 2019-10-29 03:05 UTC by icodeface

2019-10-29 03:09 UTC, icodeface commented
still some issue("bad-tx-improper-version-0" error in validation.cpp) , it needs to be fixed in https://github.com/qtumproject/qtum-neutron/pull/4

2019-12-04 03:04 UTC, xuanyan0x7c7 approved these changes

2019-12-09 22:02 UTC, Earlz requested changes
Just some minor changes needed

2019-12-09 22:02 UTC, Earlz commented on src/rpc/blockchain.cpp
> +                           RPCResult{
This is ok for now, but will need to be a different format later: https://gist.github.com/Earlz/aa235c9fa9258ae6035c26ebcd90cfe6#neutronexecutionresult

2019-12-09 22:02 UTC, Earlz commented on src/rpc/blockchain.cpp
> +        if (!ReadUniversalAddress(request.params[2].get_str(), senderAddress) || !IsValidUniversalAddress(senderAddress)) {
senderAddress should accept both UniversalAddress and standard (pubkeyhash or scripthash) base58 addresses

2019-12-09 22:02 UTC, Earlz commented on src/validation.cpp
> +                if(!((v.format == 0 && v.rootVM == 1) || (v.format == 1 && (v.rootVM == 3 || v.rootVM == 4))))
The 1/3/4 numbers should use constants so that their meaning is clear ie `...v.rootVM == NEUTRON_ROOTVM_X86` or similar

2019-12-10 02:01 UTC, icodeface commented on src/rpc/blockchain.cpp
> +        if (!ReadUniversalAddress(request.params[2].get_str(), senderAddress) || !IsValidUniversalAddress(senderAddress)) {
`ReadUniversalAddress()` can accept base58/bech32/universal hex address

2020-02-10 20:35 UTC, Earlz approved these changes

2020-02-11 04:09 UTC, icodeface commented
@Earlz fixed the merge conflicts, can u review it

2020-02-11 04:21 UTC, merged